#!/bin/bash

# Batch Lesson Expansion Script
# This will track which lessons have been expanded

echo "=== BATCH EXPANSION PROGRESS ==="
echo ""
echo "Phase 1: Business IT (COMPLETE ✅)"
echo "  - Lesson 1.1: Elevator Pitch ✅"
echo "  - Lesson 1.2: MNC Formalities ✅"
echo "  - Lesson 1.3: Networking ✅"
echo ""
echo "Phase 2: Meetings English (IN PROGRESS 🔄)"
echo "  - Lesson 1.1: Small Talk ✅"
echo "  - Lesson 1.2: Stand-ups (NEXT)"
echo "  - Lesson 1.3: Client Calls"
echo "  - Lesson 1.4: Progress Reports"
echo "  - Lesson 1.5: Technical Concepts"
echo ""
echo "Phase 3: Technical English"
echo "  - Lesson 1.1: System Design ✅"
echo "  - Lesson 1.2: Code Reviews"
echo "  - Lesson 1.3: Documentation"
echo ""
echo "Phase 4: Career Growth"
echo "  - Lesson 1.1: Resume Writing ✅"
echo "  - Lesson 1.2: LinkedIn Profile"
echo "  - Lesson 1.3: Interview Prep"
echo ""
echo "Phase 5: Email & Chat"
echo "  - Lesson 1.1: Modern Email ✅"
echo "  - Lesson 1.2: Slack Etiquette"
echo "  - Lesson 1.3: Async Communication"
echo ""
echo "Phase 6: Presentations"
echo "  - Lesson 1.1: Story Structure ✅"
echo "  - Lesson 1.2: Slide Design"
echo "  - Lesson 1.3: Q&A Handling"
echo ""
echo "Target: All 20 lessons @ 1500-2000 words each"
echo "Estimated total: 30,000-40,000 words of world-class content"
